enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[NyxMusicPlayer]
enabled = false
build-mode = "apk"
version = "auto"
uptodown-dlurl = "https://nyx-music-player.en.uptodown.com/android"
arch = "both"

[MemeGenerator]
enabled = false
version = "auto"
uptodown-dlurl = "https://meme-generator-free.en.uptodown.com/android"

[YouTube-RExtended]
enabled = true
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RExtended"
# build-mode = "both"
build-mode = "module"
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# arch = "both"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# arch = "both"

[Music-Extended]
app-name = "RExMusic"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "REx Music"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# arch = "both"

[Music-Extended]
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# arch = "both"


[Music-anddea]
enabled = false
app-name = "Music"
version = "latest"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "module"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"

[YouTube-anddea]
enabled = false
app-name = "YouTube"
version = "auto"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea"
build-mode = "module"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
